### PR TITLE
Blog post styling

### PR DESCRIPTION
**Pull request by srednakun**
Fix various styling issues in blog post view

### CODE REVIEW

**Comment by jimmynono** [comment]
Thanks Sredna. Your PR has some extraneous files in it, so I went in and manually added in the changes to my code so we have a clean pull request. For whatever reason your git ignore didn't catch and prevent the node output. You'll probably just have to manually delete that from your git. If a file is created before the gitignore is written they usually still get tracked by git. I had some trouble with last week's assignments with that.

**Comment by srednakun** [comment]
Oh yeah I was wondering why the folder was still being tracked, I'll manually delete it from my git. You didn't need to close it, it probably would have been better to just leave me a comment on the pr, so that I could just delete the file, and then merged. I think you missed the missing semicolon I put in. Did you get the paragraph spacing to work putting the wrap on the blog ul?

**Comment by srednakun** [comment]
Output folder has been removed and its all up to date with master

**Comment by pstrum** [comment]
These changes are already in our project. Great job, but no need for this PR. I don't want to close your PR, but you should close it or rebase with current master. Better yet, wait until my PR is approved because it addresses the gitignore file issues. And after that, make sure to untrack the Public/ directory. Then we'll be good to go :+1:

**Pull request merged**
